"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Create a fibonacci sequence up to a value n
def fib(n):
	next = 0
	a = 1
	b = 2
	listOfFib = [1, 2]
	while next < n:
		next = a + b
		a = b
		b = next
		listOfFib.append(next)
	return listOfFib

# Iterate through the Fibonacci list add even numbers

sum = 0
maxFibValue = 4000000
listOfFibNumbers = fib(maxFibValue)

for number in listOfFibNumbers:
	if number % 2 == 0:
		sum = sum + number

print sum


